import "./globals.css";
import "./global";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={"bg-base-100 p-4"}>
        <head>
            <script src={"https://telegram.org/js/telegram-web-app.js"}></script>
        </head>
        <body>
        {children}
        </body>
        </html>
    )
}
