import "./globals.css";
import Script from "next/script";
import {router} from "next/client";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={"bg-base-100 p-4"}>
        <head>
            <Script src="https://telegram.org/js/telegram-web-app.js" onReady={() => {
                if (typeof window !== 'undefined') {
                    // @ts-expect-error todo
                    window.Telegram.WebApp.BackButton.isVisible = true
                    // @ts-expect-error todo
                    window.Telegram.WebApp.BackButton.onClick(() => {
                        router.back()
                    })
                }
            }}></Script>
        </head>
        <body>
        {children}
        </body>
        </html>
    )
}
